### ISSUE TITLE
Error after executing the minibot.py file

### ISSUE THREAD

**Issue by PascalBaehr** [alfred82santa/whalesong#5] opened 2018-07-09 09:14 UTC
Hey! 
I got a problem with execute the minibot.py :/
Hope you can help me :)

**Versions:**
Ubuntu 18.04 is the active os - I tested Debian 9 bevore
Geckodriver: v0.21.0
Selenium & Firefox: newest Version from setup.

Setup works without errors.
I get this error two times after I send `python3 examples/minibot.py`
`
Traceback (most recent call last):
  File "examples/minibot.py", line 125, in <module>
    bot.loop.run_until_complete(bot.start())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "examples/minibot.py", line 116, in start
    await self._driver.start()
  File "/bot/servo000/whalesong/__init__.py", line 43, in start
    await self._driver.start_driver()
  File "/bot/servo000/whalesong/driver.py", line 56, in start_driver
    await self._start_fut
  File "/bot/servo000/whalesong/driver.py", line 83, in start_driver
    self.driver = await self._start_fut
  File "/bot/servo000/whalesong/driver.py", line 52, in _run_async
    return await self.loop.run_in_executor(self._pool_executor, partial(method, *args, **kwargs))
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/bot/servo000/whalesong/driver.py", line 76, in start
    service_args=['--marionette-port', '2828'])
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
`

Thanks!

**Comment by alfred82santa** [comment] 2018-07-09 16:50
Hi, I need more info. It works in my machine.

```bash
$ geckodriver --version
geckodriver 0.21.0

The source code of this program is available from
testing/geckodriver in https://hg.mozilla.org/mozilla-central.

This program is subject to the terms of the Mozilla Public License 2.0.
You can obtain a copy of the license at https://mozilla.org/MPL/2.0/.
$ firefox --version
Mozilla Firefox 61.0
$ pip3 freeze | grep selenium
selenium==3.12.0
$ PYTHONPATH=.:$PYTHONPATH python examples/minibot.py 
Monitor stream
Stream value: SYNCING
```
Are you trying it with no X server? It looks it is trying to start firefox with some strange capabilities.

**Comment by PascalBaehr** [comment] 2018-07-09 20:05
Hey,

cant find the problem. What you mean with "no X Server"?
Is it okay to start the script with root user? I see you started it with normal user rights ($).

Firefox is fresh installed also like the ubuntu server.

Execute command without root permissions:

```
pascalbaehr@bot-s01:/bot/servo000$ PYTHONPATH=.:$PYTHONPATH python3 examples/minibot.py
Traceback (most recent call last):
  File "examples/minibot.py", line 124, in <module>
    bot = Minibot()
  File "examples/minibot.py", line 20, in __init__
    loop=loop
  File "/bot/servo000/whalesong/__init__.py", line 22, in __init__
    loop=loop))
  File "/bot/servo000/whalesong/driver.py", line 24, in __init__
    self._profile = FirefoxProfile(profile_directory=abspath(profile) if profile else None)
  File "/bot/servo000/whalesong/firefox_profile.py", line 18, in __init__
    copyfile(path.join(TEMPLATE_DIR, 'addons.json'), path.join(self.profile_dir, 'addons.json'))
  File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/bot/servo000/examples/profile/addons.json'
```


Some infos:

```
root@bot-s01:/pushrme/servo000# firefox --version
Mozilla Firefox 61.0
root@bot-s01:/pushrme/servo000# pip3 freeze | grep selenium
selenium==3.13.0
root@bot-s01:/pushrme/servo000# geckodriver --version
geckodriver 0.21.0

The source code of this program is available from
testing/geckodriver in https://hg.mozilla.org/mozilla-central.

This program is subject to the terms of the Mozilla Public License 2.0.
You can obtain a copy of the license at https://mozilla.org/MPL/2.0/.
```

Thanks!

**Comment by alfred82santa** [comment] 2018-07-09 20:38
Ok, I think the problem is how minibot instantiate driver. https://github.com/alfred82santa/whalesong/blob/master/examples/minibot.py#L17
Try to add `headless=True`. By default, examples don't use headless, so they need a X server running (X server is the graphic interface in Unix systems, more or less, nowadays there are more servers: wayland, mir, etc...).
Without that param if you test the code in your machine, if it runs, you will see a firefox window. I use it to debug. When you want to run this kind of software in a server or in a docker or something like that you must be sure you don't need a X server. In this case just with this param is enough. In other cases maybe you need a fake X server.

**Comment by alfred82santa** [comment] 2018-07-09 20:48
On the other hand, you problems when it is executed with no root permissions are because you are using a profile directory where you cannot write. Just change owner or permission to resolve it. 

Never run untrusted software as root.

**Comment by PascalBaehr** [comment] 2018-07-09 20:55
Hey! 
Thanks for your quick help!
Now it work! I already thought that I have to put the headless mode in the profile parameter.
Thanks for declaration of X Server - I already used it bevore but did not think about it anymore.

The script start with normal user:
```
user@bot-s01:/bot/servo000$ PYTHONPATH=.:$PYTHONPATH python3 examples/minibot.py
Monitor stream
Stream value: DISCONNECTED
```

Actual the Bot is DISCONNECTED - I have to try to get the QR Code to connect it.
Is there an option to get the QR as a png file? (Is this question okay here?)

Thanks for your help!

**Comment by alfred82santa** [comment] 2018-07-09 21:00
Not is this example. But, you could run https://github.com/alfred82santa/whalesong/blob/master/examples/statemonitor.py
It saves qr in a file https://github.com/alfred82santa/whalesong/blob/master/examples/statemonitor.py#L68. You could run it with same profile and scan QR image. After that, firefox profile will keep session when you run minibot.

Be careful, QR image change every minute... you must scan it quickly...

**Comment by alfred82santa** [comment] 2018-07-09 21:04
I going to close this issue, if you have any other problem, please feel free to open a new one.

**Comment by PascalBaehr** [comment] 2018-07-09 21:05
Thank you very much for your good and quick help!

**Closed** 2018-07-09 21:04 UTC
